### ISSUE TITLE
Unable to execute on Windows 10 platform

### ISSUE THREAD

**Issue by virsto** [Tereshchenkolab/paper-ecg#12]
I have included some results from the installation and attempt to execute the code: 1) verification using Python 3.6.7,  2) results running requirements.txt, and 3)  execution of fbs run : 
``
1)
C:\PythonTestCode\Graph-to-ECG\paper-ecg-1.0.0>c:/python36/python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

2)
C:\PythonTestCode\Graph-to-ECG\paper-ecg-1.0.0>c:/python36/python -m pip install -r requirements.txt
Requirement already satisfied: fbs==0.9.0 in c:\python36\lib\site-packages (from -r requirements.txt (line 2)) (0.9.0)
Requirement already satisfied: PyQt5==5.15.1 in c:\python36\lib\site-packages (from -r requirements.txt (line 3)) (5.15.1)
Requirement already satisfied: numpy in c:\python36\lib\site-packages (from -r requirements.txt (line 6)) (1.19.5)
Requirement already satisfied: scipy==1.4.1 in c:\python36\lib\site-packages (from -r requirements.txt (line 8)) (1.4.1)
Requirement already satisfied: opencv-python-headless>=4.4 in c:\python36\lib\site-packages (from -r requirements.txt (line 9)) (4.6.0.66)
Requirement already satisfied: qimage2ndarray in c:\python36\lib\site-packages (from -r requirements.txt (line 10)) (1.9.0)
Requirement already satisfied: mypy in c:\python36\lib\site-packages (from -r requirements.txt (line 13)) (0.971)
Requirement already satisfied: pathlib in c:\python36\lib\site-packages (from -r requirements.txt (line 14)) (1.0.1)
Requirement already satisfied: dataclasses in c:\python36\lib\site-packages (from -r requirements.txt (line 15)) (0.8)
Requirement already satisfied: PyInstaller==3.4 in c:\python36\lib\site-packages (from fbs==0.9.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\python36\lib\site-packages (from PyQt5==5.15.1->-r requirements.txt (line 3)) (12.9.0)
Requirement already satisfied: pefile>=2017.8.1 in c:\python36\lib\site-packages (from PyInstaller==3.4->fbs==0.9.0->-r requirements.txt (line 2)) (2021.9.3)
Requirement already satisfied: macholib>=1.8 in c:\python36\lib\site-packages (from PyInstaller==3.4->fbs==0.9.0->-r requirements.txt (line 2)) (1.16.2)
Requirement already satisfied: setuptools in c:\python36\lib\site-packages (from PyInstaller==3.4->fbs==0.9.0->-r requirements.txt (line 2)) (59.6.0)
Requirement already satisfied: pywin32-ctypes in c:\python36\lib\site-packages (from PyInstaller==3.4->fbs==0.9.0->-r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: altgraph in c:\python36\lib\site-packages (from PyInstaller==3.4->fbs==0.9.0->-r requirements.txt (line 2)) (0.17.2)
Requirement already satisfied: tomli>=1.1.0 in c:\python36\lib\site-packages (from mypy->-r requirements.txt (line 13)) (1.2.3)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\python36\lib\site-packages (from mypy->-r requirements.txt (line 13)) (0.4.3)
Requirement already satisfied: typed-ast<2,>=1.4.0 in c:\python36\lib\site-packages (from mypy->-r requirements.txt (line 13)) (1.5.4)
Requirement already satisfied: typing-extensions>=3.10 in c:\python36\lib\site-packages (from mypy->-r requirements.txt (line 13)) (4.1.1)
Requirement already satisfied: future in c:\python36\lib\site-packages (from pefile>=2017.8.1->PyInstaller==3.4->fbs==0.9.0->-r requirements.txt (line 2)) (0.18.2)

C:\PythonTestCode\Graph-to-ECG\paper-ecg-1.0.0>

3)
C:\PythonTestCode\Graph-to-ECG\paper-ecg-1.0.0>c:/python36/python -m fbs run
Traceback (most recent call last):
  File "C:\PythonTestCode\Graph-to-ECG\paper-ecg-1.0.0\src\main\python\Main.py", line 12, in <module>
    from controllers.MainController import MainController
  File "C:\PythonTestCode\Graph-to-ECG\paper-ecg-1.0.0\src\main\python\controllers\MainController.py", line 9, in <module>
    import cv2
  File "c:\python36\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "c:\python36\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "c:\python36\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "c:\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\python36\lib\site-packages\cv2\gapi\__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline``

**Comment by arnaudlenain** [comment]
py -3.6 -m fbs run
